apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: predictive-maintenance-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: predictive-maintenance-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio:9000"
            - name: MLFLOW_SERVER_ALLOWED_HOSTS
              value: "mlflow,mlflow:5000,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000,[::1]:5000,0.0.0.0,10.*"
          command:
            - mlflow
          args:
            - server
            - --backend-store-uri
            - sqlite:////mlflow/mlflow.db
            - --default-artifact-root
            - s3://mlflow
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --allowed-hosts
            - "mlflow,mlflow:5000,localhost,localhost:5000,127.0.0.1,127.0.0.1:5000,[::1]:5000,0.0.0.0,10.*"
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: mlflow-data
          persistentVolumeClaim:
            claimName: mlflow-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
