apiVersion: v1
kind: Secret
metadata:
  name: predictive-maintenance-secrets
  labels:
    app: predictive-maintenance-api
type: Opaque
stringData:
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"
