apiVersion: v1
kind: Secret
metadata:
  name: predictive-maintenance-secrets
  labels:
    app: predictive-maintenance-api
type: Opaque
stringData:
  MINIO_ROOT_USER: "change-me-minio-root-user"
  MINIO_ROOT_PASSWORD: "change-me-minio-root-password"
  AWS_ACCESS_KEY_ID: "change-me-aws-access-key-id"
  AWS_SECRET_ACCESS_KEY: "change-me-aws-secret-access-key"
  GRAFANA_ADMIN_PASSWORD: "change-me-grafana-admin-password"
