apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}-api
spec:
  type: NodePort
  selector:
    app: {{ cookiecutter.project_slug }}-api
  ports:
    - name: http
      port: {{ cookiecutter.fastapi_port }}
      targetPort: {{ cookiecutter.fastapi_port }}
      nodePort: 30080
